### PR TITLE
Add notes for Designing GraphQL Schemas

### PR DESCRIPTION
**Pull request by aromanarguello**

### CODE REVIEW

**Comment by lsminter** [comment]
Great notes! I love the uses of the emojis. You also had a lot of really good resources. A couple last minute things before I get this uploaded to egghead. We need a Table of Contents in the README. You have two lesson 9's. The second one needs to be number 10 and the rest need to be numbered accordingly. Lastly, when you are adding these emoji's to the code blocks, they have to be commented out. If they aren't, it'll break the code if someone copy/pasts your code into their code editor. So all of those will need to be commented out.

**Review by lsminter — COMMENTED** [review]
Great notes! I love the uses of the emojis. You also had a lot of really good resources. A couple last minute things before I get this uploaded to egghead. We need a Table of Contents in the README. You have two lesson 9's. The second one needs to be number 10 and the rest need to be numbered accordingly. Lastly, when you are adding these emoji's to the code blocks, they have to be commented out. If they aren't, it'll break the code if someone copy/pasts your code into their code editor. So all of those will need to be commented out.

**Comment by aromanarguello** [comment]
@lsminter Great catch, thanks! Completely forgot about it. Will fix tonight :)

**Comment by aromanarguello** [comment]
@lsminter comments addressed :)

**Pull request merged**
