### PR TITLE
Closure and callbacks v2

### PR DESCRIPTION
**Pull request by horacioh**
[x] 38. Create a Custom useBroadcaster Hook
[x] 39. Pass a Listener to a useCallback Hook
[x] 40. Create a Custom useListener Hook Around useCallback
[x] 41. Explaining the useListener Code
[x] 42. Handling an Enter Keypress with useListener and React
[x] 43. Share the Same Broadcaster Values Across Multiple Listeners
[x] 44. Limit to a Single Shared Broadcaster Each New Event
[x] 45. Combine Two Broadcasters to Compare Values
[x] 46. Compose Operators to Implement Game Logic

### CODE REVIEW

**Review by laurosilvacom — APPROVED** [review]
@horacioh these notes are on point! 😄 Thanks for taking on these additional notes.

**Comment by horacioh** [comment]
oh, no need for the links below (previous and next lesson)?

**Comment by laurosilvacom** [comment]
We are splitting the course into several sections (mini-courses) but keeping all the notes together. From my perspective, it doesn't make sense to link between the _previous_ and _next_ lessons since the progression won't necessarily be linear.

**Comment by horacioh** [comment]
that make sense!

💪🏻🤟🏼

**Pull request merged**
