### PR TITLE
Update 09-show-video-in-gatsby-from-remote-participants-with-react-ho…

### PR DESCRIPTION
**Pull request by ofu997**
Initially my app crashed with more than one participant. I looked in the source code and I'd like to add the differences, mainly the way we define localTrack and handleParticipant.

### CODE REVIEW

**Comment by laurosilvacom** [comment]
Great approach @ofu997! Thanks for contributing  🙌

**Comment by Botfacke** [comment]
> Initially my app crashed with more than one participant. I looked in the source code and I'd like to add the differences, mainly the way we define localTrack and handleParticipant.

**Comment by Botfacke** [comment]
> Initially my app crashed with more than one participant. I looked in the source code and I'd like to add the differences, mainly the way we define localTrack and handleParticipant.

**Review by Botfacke — COMMENTED** [review]
https://patch-diff.githubusercontent.com/raw/eggheadio/eggheadio-course-notes/pull/126.patch

**Review by Botfacke — COMMENTED** [review]
ofu997:patch-2

**Pull request merged**
